# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180826_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='convalida1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corso',
            name='convalida2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corso',
            name='convalida3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corso',
            name='convalida4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corso',
            name='convalida5',
            field=models.IntegerField(default=0),
        ),
    ]
