# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20180828_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convalida', models.BooleanField(default=False)),
                ('alunno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approvazione',
                'verbose_name_plural': 'Approvazioni',
            },
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='convalida1',
            new_name='convalida',
        ),
        migrations.RemoveField(
            model_name='corso',
            name='convalida2',
        ),
        migrations.RemoveField(
            model_name='corso',
            name='convalida3',
        ),
        migrations.RemoveField(
            model_name='corso',
            name='convalida4',
        ),
        migrations.RemoveField(
            model_name='corso',
            name='convalida5',
        ),
        migrations.AddField(
            model_name='approvazione',
            name='corso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Corso'),
        ),
    ]
