# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-29 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180829_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvazione',
            name='alunno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvazione',
            name='corso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Corso'),
        ),
    ]
